dist: trusty
sudo: false

cache:
  directories:
  - "$HOME/.cache"
  
env:
  global:
  - secure: coYmI9CDAm9cigIBsdxt3sHld6TCafFAzeO/ewWWxf+/cdB7Yq5WJvBVxKsnG2jBl/h7rnZQP3x57ZfJ/F+dHg3fv+Z/LmX5JEdN83MFnX62HpYnBv5FDDT3zd+cagwfJk9m1hNw6qGALqCiuDnDbQ0N6Ql+jCHS3CHX1dxDSmDrAJM6sjqJu3qrP8olSG8RldGQcjnhfh+5r59VWc+djg9ted7Co3/F1iCzNH84zt1PrUyq1gw8nE1toBj+M487THo9ONNhgLTZjjYJiXPyk9zAnh/8qpMSalFKEz0LIR4nU1m50xVutQNny0CbvI149wAv+AvuPgjluuo1UzlNei9wDhgB3TkmKBSztFlJXICs0oMk7vFhFetgk99RpAF4CjAeJ9OJwEUHwbWAWuphiAhTnqERftZIOzN+AyS1ZJP83nb+dkPaMibeMmyy73TcOmVm0cWUrV1ysaf4Ntl1rz0UK51yAaohiJdqtgZw1D254e001Agk0KzbfgsTHBcICIyYaWOTQDFTjoQNelFYMJ488qX4xybGpbH6Vszr0S/qGqLb2l+Ljgt1U7HJhMiOmsWdzeXiFiITJsvl6SuVd+fi9Sy6DD4s841VsFedGn4yketJpUjAr9zGwQFkUWyKRa/L5lt9gEkLTIi0bVLNTpLLXlgPF5xKUieOF4tV/p8=

stages:
- name: build
- name: deploy

jobs:
  include:
  - stage: build
    language: c
    install:
    - gem install fpm
    env:
    - PROJECT=debian
    - STAGE=build
  - stage: build
    language: java
    jdk: oraclejdk8
    env:
    - PROJECT=maven
    - STAGE=build
  - stage: build
    language: java
    jdk: oraclejdk8
    env:
    - PROJECT=gradle
    - STAGE=build
  - stage: build
    language: python
    python: 2.7
    install:
    - pip install tox
    env:
    - PROJECT=python
    - STAGE=build
  - stage: build
    language: c
    install:
    - gem install fpm
    env:
    - PROJECT=redhat
    - STAGE=build
  - stage: build
    language: ruby
    rvm: 2.2
    install:
    - gem install rake
    gemfile: bindings/ruby/src/Gemfile
    env:
    - PROJECT=ruby
    - STAGE=build

script:
  - set -e
  - if [[ "$STAGE" == "build" ]]; then ./scripts/build.sh $PROJECT; fi

before_deploy:
  - pyenv global 2.7
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install --upgrade wheel
  - pip install cloudsmith-cli
  - pip install twine
  
deploy:
  provider: script
  skip_cleanup: true
  script: "./scripts/deploy.sh $PROJECT"
  on:
    branch: master
    
notifications:
  email:
    on_failure: always
    on_success: change
  slack:
    secure: qm4pgQYyTwTAkH0jTJxwMnvkWDhXEbulGRZUbMZbq2kvDAgnfWmusuvWNw0iGl9ArWpzgJxKKg1+hElKSuLgtTo4YGn78LoqhRTdZdNOSr+4/C8JRFeBZJMJUUqVzqWWdojuX5HogEjR6SmH+sr5KQkGJKaFanWNETQ8aaRSj1omt0dcLRoFQVNd2CXwo6qwRY/8r+a5sLBtOwSY/wtoTnBT6ebtNWctsyYmBClbJsUXlXlwRK7npDFz6S2f+6/0yiXoACz5XZLkwghMsX465rSMep9LVcFARAyZide2b+nkSqPdyFje4T7APhEWNCtXHg1AJSHw3KsQEXmnifJFdgRfTu8v7vM1dnBlTdXaRpavHJOVS0TEIvKdd5vmemNMPVVVMbTcQXwxSkl8oSacGjO8vbK91WGTJI3psoUKp7EP0MYeq9TAZpoZJHpemPg7H5fZdA5UyBFROaU7gsNb96JUDuGQAm+7AmrYx1YFqTjFioHtVF1XPs4elgkHEu1+D6kq9doKMQ+M38yIj1KkRtLjuEFKZ286joeoCrisPaFgsPsAHG46q1pqtIoXjQZKAwIvMbB1K7OuK5KO4oY+ppOZPZi56HLVh6oLzK4T6JA64JBIUo77dzOFO0hy/0riH6iEaOpG4hkt4f1sVBpGyTQxTpY/6Yzf8gQ2oJUvo3M=
